/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequestDto"];
                    "text/json": components["schemas"]["RegisterRequestDto"];
                    "application/*+json": components["schemas"]["RegisterRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfSigninResponseDto"];
                        "application/json": components["schemas"]["ResultOfSigninResponseDto"];
                        "text/json": components["schemas"]["ResultOfSigninResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfSigninResponseDto"];
                        "application/json": components["schemas"]["ResultOfSigninResponseDto"];
                        "text/json": components["schemas"]["ResultOfSigninResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfstring"];
                        "application/json": components["schemas"]["ResultOfstring"];
                        "text/json": components["schemas"]["ResultOfstring"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        Title?: string;
                        /** Format: uuid */
                        UserId?: string;
                        /** Format: uuid */
                        CategoryId?: string;
                        Description?: string;
                        CoverImage?: components["schemas"]["IFormFile"];
                        File?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfBookResponse"];
                        "application/json": components["schemas"]["ResultOfBookResponse"];
                        "text/json": components["schemas"]["ResultOfBookResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/booksbycategory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/allCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfListOfCategoryNameResponseDto"];
                        "application/json": components["schemas"]["ResultOfListOfCategoryNameResponseDto"];
                        "text/json": components["schemas"]["ResultOfListOfCategoryNameResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeCategoryRequestDto"];
                    "text/json": components["schemas"]["ChangeCategoryRequestDto"];
                    "application/*+json": components["schemas"]["ChangeCategoryRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfCategoryNameResponseDto"];
                        "application/json": components["schemas"]["ResultOfCategoryNameResponseDto"];
                        "text/json": components["schemas"]["ResultOfCategoryNameResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfUserProfileDto"];
                        "application/json": components["schemas"]["ResultOfUserProfileDto"];
                        "text/json": components["schemas"]["ResultOfUserProfileDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            author?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            categoryId?: null | string;
            categoryName?: null | string;
            description?: null | string;
            /** Format: date-time */
            createdAt?: string;
            coverImageUrl?: null | string;
            fileUrl?: null | string;
        };
        CategoryNameResponseDto: {
            /** Format: uuid */
            categoryId: string;
            name: string;
        };
        ChangeCategoryRequestDto: {
            categoryId: string;
            newName: string;
            newDescription: null | string;
        };
        Error: {
            message: string;
            type: components["schemas"]["ErrorType"];
        };
        ErrorType: number;
        /** Format: binary */
        IFormFile: string;
        LoginRequestDto: {
            email: string;
            password: string;
        };
        RegisterRequestDto: {
            username: string;
            email: string;
            password: string;
            phoneNumber: null | string;
            roles?: components["schemas"]["UserRoles"];
        };
        ResultOfBookResponse: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: components["schemas"]["BookResponse"];
            error?: components["schemas"]["Error"];
        };
        ResultOfCategoryNameResponseDto: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: components["schemas"]["CategoryNameResponseDto"];
            error?: components["schemas"]["Error"];
        };
        ResultOfListOfCategoryNameResponseDto: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: null | components["schemas"]["CategoryNameResponseDto"][];
            error?: components["schemas"]["Error"];
        };
        ResultOfSigninResponseDto: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: components["schemas"]["SigninResponseDto"];
            error?: components["schemas"]["Error"];
        };
        ResultOfstring: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: null | string;
            error?: components["schemas"]["Error"];
        };
        ResultOfUserProfileDto: {
            isSuccess?: boolean;
            isFailure?: boolean;
            value?: components["schemas"]["UserProfileDto"];
            error?: components["schemas"]["Error"];
        };
        SigninResponseDto: {
            /** Format: uuid */
            userId: string;
        };
        UserProfileDto: {
            /** Format: uuid */
            userId: string;
            username: string;
            email: string;
            image: null | string;
            roles: string;
        };
        /** @default Reader */
        UserRoles: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
