/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/book/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        Title?: string;
                        /** Format: uuid */
                        CategoryId?: string;
                        Description?: string;
                        /** Format: double */
                        Price?: number | string;
                        CoverImage?: components["schemas"]["IFormFile"];
                        File?: components["schemas"]["IFormFile"];
                        /** Format: uuid */
                        UserId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfCreateBookResponse"];
                        "application/json": components["schemas"]["ResultOfCreateBookResponse"];
                        "text/json": components["schemas"]["ResultOfCreateBookResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** Format: uuid */
                        BookId?: string;
                        Title?: string;
                        Description?: string;
                        /** Format: double */
                        Price?: number | string;
                        /** Format: uuid */
                        CategoryId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** Format: uuid */
                        BookId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** Format: uuid */
                        BookId?: string;
                        BookStatus?: components["schemas"]["BookStatus"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                    PageNumber?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfIEnumerableOfBookSummaryResponse"];
                        "application/json": components["schemas"]["ResultOfIEnumerableOfBookSummaryResponse"];
                        "text/json": components["schemas"]["ResultOfIEnumerableOfBookSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/authorbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfIEnumerableOfAuthorBookResponse"];
                        "application/json": components["schemas"]["ResultOfIEnumerableOfAuthorBookResponse"];
                        "text/json": components["schemas"]["ResultOfIEnumerableOfAuthorBookResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    BookId?: string;
                    UserId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfGetBookResponse"];
                        "application/json": components["schemas"]["ResultOfGetBookResponse"];
                        "text/json": components["schemas"]["ResultOfGetBookResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    BookId?: string;
                    UserId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileResult"];
                        "application/json": components["schemas"]["FileResult"];
                        "text/json": components["schemas"]["FileResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    BookId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileResult"];
                        "application/json": components["schemas"]["FileResult"];
                        "text/json": components["schemas"]["FileResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/bookbio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfBookBioResponse"];
                        "application/json": components["schemas"]["ResultOfBookBioResponse"];
                        "text/json": components["schemas"]["ResultOfBookBioResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfIEnumerableOfAllCategoryResponse"];
                        "application/json": components["schemas"]["ResultOfIEnumerableOfAllCategoryResponse"];
                        "text/json": components["schemas"]["ResultOfIEnumerableOfAllCategoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditCategoryRequestCommand"];
                    "text/json": components["schemas"]["EditCategoryRequestCommand"];
                    "application/*+json": components["schemas"]["EditCategoryRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/category/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddCategoryRequestCommand"];
                    "text/json": components["schemas"]["AddCategoryRequestCommand"];
                    "application/*+json": components["schemas"]["AddCategoryRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfAddCategoryResponse"];
                        "application/json": components["schemas"]["ResultOfAddCategoryResponse"];
                        "text/json": components["schemas"]["ResultOfAddCategoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequestCommand"];
                    "text/json": components["schemas"]["CreateOrderRequestCommand"];
                    "application/*+json": components["schemas"]["CreateOrderRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfOrderResponse"];
                        "application/json": components["schemas"]["ResultOfOrderResponse"];
                        "text/json": components["schemas"]["ResultOfOrderResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveOrderCommand"];
                    "text/json": components["schemas"]["ApproveOrderCommand"];
                    "application/*+json": components["schemas"]["ApproveOrderCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReviewRequestCommand"];
                    "text/json": components["schemas"]["CreateReviewRequestCommand"];
                    "application/*+json": components["schemas"]["CreateReviewRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    BookId?: string;
                    Take?: number | string;
                    Skip?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfIEnumerableOfGetReviewResponse"];
                        "application/json": components["schemas"]["ResultOfIEnumerableOfGetReviewResponse"];
                        "text/json": components["schemas"]["ResultOfIEnumerableOfGetReviewResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequestCommand"];
                    "text/json": components["schemas"]["RegisterRequestCommand"];
                    "application/*+json": components["schemas"]["RegisterRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfSigninResponse"];
                        "application/json": components["schemas"]["ResultOfSigninResponse"];
                        "text/json": components["schemas"]["ResultOfSigninResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestCommand"];
                    "text/json": components["schemas"]["LoginRequestCommand"];
                    "application/*+json": components["schemas"]["LoginRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfSigninResponse"];
                        "application/json": components["schemas"]["ResultOfSigninResponse"];
                        "text/json": components["schemas"]["ResultOfSigninResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePasswordRequestCommand"];
                    "text/json": components["schemas"]["UpdatePasswordRequestCommand"];
                    "application/*+json": components["schemas"]["UpdatePasswordRequestCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Result"];
                        "application/json": components["schemas"]["Result"];
                        "text/json": components["schemas"]["Result"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResultOfProfileResponse"];
                        "application/json": components["schemas"]["ResultOfProfileResponse"];
                        "text/json": components["schemas"]["ResultOfProfileResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        username?: string;
                        deleteCurrentImage?: boolean;
                        image?: components["schemas"]["IFormFile"];
                        /** Format: uuid */
                        UserId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddCategoryRequestCommand: {
            name: string;
            description: null | string;
        };
        AddCategoryResponse: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            description?: null | string;
        };
        AllCategoryResponse: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            description?: null | string;
        };
        ApproveOrderCommand: {
            /** Format: uuid */
            orderId: string;
        };
        AuthorBookResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            categoryName: null | string;
            /** Format: double */
            price: number | string;
            bookStatus: string;
            /** Format: int32 */
            order: number | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
            coverImageUrl: null | string;
            /** Format: double */
            averageRate: number | string;
        };
        BookBioResponse: {
            /** Format: int32 */
            totalBook: number | string;
            /** Format: int32 */
            pulibshed: number | string;
            /** Format: int32 */
            totalOrder: number | string;
        };
        /** @enum {unknown} */
        BookStatus: "Accepted" | "Rejected" | "Pending";
        BookSummaryResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            author: string;
            categoryName: null | string;
            /** Format: double */
            price: number | string;
            /** Format: int32 */
            order: number | string;
            bookStatus: string;
            /** Format: date-time */
            publishedAt: string;
            coverImageUrl: null | string;
        };
        CreateBookResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            author: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            categoryId: null | string;
            categoryName: null | string;
            /** Format: double */
            price: number | string;
            bookStatus: string;
            /** Format: int32 */
            order: number | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
            coverImageUrl: null | string;
            reviews: null | components["schemas"]["ReviewResponse"][];
            /** Format: double */
            averageRate: number | string;
            /** Format: int32 */
            pageCount: number | string;
            /** Format: int64 */
            fileSizeInBytes: number | string;
            /** @default false */
            hasUserReviewed: boolean;
        };
        CreateOrderRequestCommand: {
            /** Format: uuid */
            bookId: string;
        };
        CreateReviewRequestCommand: {
            /** Format: uuid */
            bookId: string;
            comment: null | string;
            /**
             * Format: int32
             * @default 1
             */
            rating: number | string;
        };
        EditCategoryRequestCommand: {
            categoryId: string;
            newName: string;
            newDescription: null | string;
        };
        EntityTagHeaderValue: {
            tag?: components["schemas"]["StringSegment"];
            isWeak?: boolean;
        };
        FileResult: {
            contentType?: null | string;
            fileDownloadName?: null | string;
            /** Format: date-time */
            lastModified?: null | string;
            entityTag?: null | components["schemas"]["EntityTagHeaderValue"];
            enableRangeProcessing?: boolean;
        };
        GetBookResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            author: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            categoryId: null | string;
            categoryName: null | string;
            /** Format: double */
            price: number | string;
            bookStatus: string;
            /** Format: int32 */
            order: number | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
            coverImageUrl: null | string;
            /** Format: double */
            averageRate: number | string;
            /** Format: int32 */
            pageCount: number | string;
            /** Format: int64 */
            fileSizeInBytes: number | string;
            /** Format: int32 */
            reviewCount: number | string;
            /** @default false */
            hasUserReviewed: boolean;
        };
        GetReviewResponse: {
            /** Format: uuid */
            reviewId: string;
            comment: string;
            /** Format: int32 */
            rating: number | string;
            username: string;
            image: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            userId: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        LoginRequestCommand: {
            email: string;
            password: string;
        };
        OrderResponse: {
            /** Format: uuid */
            orderId: string;
            status: components["schemas"]["OrderStatus"];
        };
        OrderStatus: number;
        ProfileResponse: {
            /** Format: uuid */
            userId: string;
            username: string;
            email: string;
            image: null | string;
            roles: string;
            /**
             * Format: double
             * @default 15
             */
            balance: number | string;
        };
        RegisterRequestCommand: {
            username: string;
            email: string;
            password: string;
            phoneNumber: null | string;
            roles?: components["schemas"]["UserRoles"];
        };
        Result: {
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfAddCategoryResponse: {
            value?: components["schemas"]["AddCategoryResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfBookBioResponse: {
            value?: components["schemas"]["BookBioResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfCreateBookResponse: {
            value?: components["schemas"]["CreateBookResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfGetBookResponse: {
            value?: components["schemas"]["GetBookResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfIEnumerableOfAllCategoryResponse: {
            value?: null | components["schemas"]["AllCategoryResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfIEnumerableOfAuthorBookResponse: {
            value?: null | components["schemas"]["AuthorBookResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfIEnumerableOfBookSummaryResponse: {
            value?: null | components["schemas"]["BookSummaryResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfIEnumerableOfGetReviewResponse: {
            value?: null | components["schemas"]["GetReviewResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfOrderResponse: {
            value?: components["schemas"]["OrderResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfProfileResponse: {
            value?: components["schemas"]["ProfileResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ResultOfSigninResponse: {
            value?: components["schemas"]["SigninResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        ReviewResponse: {
            /** Format: uuid */
            reviewId: string;
            comment: string;
            /** Format: int32 */
            rating: number | string;
            username: string;
            image: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        SigninResponse: {
            /** Format: uuid */
            userId: string;
        };
        StringSegment: {
            buffer?: null | string;
            /** Format: int32 */
            offset?: number | string;
            /** Format: int32 */
            length?: number | string;
            value?: null | string;
            hasValue?: boolean;
        };
        UpdatePasswordRequestCommand: {
            currentPassword: string;
            newPassword: string;
        };
        /** @default Reader */
        UserRoles: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
