import type { Metadata } from "next";
import { IBM_Plex_Sans, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { cn } from "@/lib/utils";
import { auth } from "@/../auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/layout/footer";

const instrumentSerifHeading = Instrument_Serif({ subsets: ['latin'], weight: ['400'], variable: '--font-heading' });

const ibmPlexSans = IBM_Plex_Sans({ subsets: ['latin'], variable: '--font-sans' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();


  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased",  "font-sans", ibmPlexSans.variable, instrumentSerifHeading.variable)}
      suppressHydrationWarning
    >

      <body>

        <ThemeProvider attribute="class" defaultTheme="dark">
          <SessionProvider session={session}>
            <Header />
            <main>{children}</main>
            <Footer />
          </SessionProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}